version: '3.1'

networks:
  common:
    driver: ${NETWORKS_DRIVER}

services:
  #  redis:
  #    image: redis
  #    container_name: tsdd_redis
  #    environment:
  #      - TZ=${TZ}
  #    volumes:
  #      - ${DATA_PATH_HOST}/redis:/data # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
  #    ports:
  #      - "${REDIS_PORT}:6379" # 设置容器6379端口映射指定宿主机端口
  #    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
  #    networks:
  #      - common
  #    restart: always
  #
  #  mysql:
  #    image: mysql
  #    container_name: tsdd_mysql
  #    environment:
  #      - TZ=${TZ}
  #      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # 设置 Mysql root 用户密码
  #      - MYSQL_SQL_MODE="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
  #    privileged: true
  #    volumes:
  #      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Mysql 数据的目录挂载到容器中 /var/lib/mysql 目录
  #    ports:
  #      - "${MYSQL_PORT}:3306" # 设置容器3306端口映射指定宿主机端口
  #    networks:
  #      - common
  #    restart: always
  wukongim: # wukongim底层通讯服务
    image: zyuan909/wukongim:latest
    container_name: tsdd_im
    restart: always
    volumes:
      - ${DATA_PATH_HOST}:/root/wukongim
    environment:
      WK_MODE: "debug"
      WK_EXTERNAL_IP: "192.168.99.219"
    ports:
      - 35001:5001 # http api 端口
      - 35100:5100 # tcp端口
      - 35200:5200 # websocket端口
      - 35300:5300 # monitor端口
  minio: # minio文件管理服务
    image: minio/minio:latest # use a remote image
    restart: always
    command: "server /data --console-address ':9001'"
    ports:
      - "39000:9000"
      - "39001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/minio:/data
  tsdd:
    image: zyuan909/tsdd_server:latest
    container_name: tsdd_server
    ports:
      - "38090:8090"
      - "36979:6979"
    volumes:
      - ${DATA_PATH_HOST}/tsdd_server:/configs
      - ${DATA_PATH_HOST}/tsdd_server/push:/configs/push
    networks:
      - common
    depends_on:
      - wukongim
